#!/bin/bash

exec 1>>/dev/shm/sapha.check
exec 2>&1

rsc=$1
act=$2
stat=$3
rc=1

PATH=$PATH:/usr/sbin 
crm_resource -O -r $rsc | grep "${rsc}_${act}_.*: ${stat}"  && rc=0

echo "$0 exists with rc=$rc"
exit $rc
