#!/bin/bash
#
#############################################################################
#
# do_resource_change
#
# request an operation or other change of a specified cluster resource
#
#############################################################################
#
# Author: Fabian Herschel
#
# (c) SUSE Linux Products GmbH
#
# License: GPL v2
#
#############################################################################
#
# Parameters: <resource> <action> [<node>]
#
# <action> could be are:
#       stop 
#       start
#       migrate ( with optinal destination node )
#

exec 1>>/dev/shm/sapha.change
exec 2>&1

rsc=$1
act=$2
node=$3
rc=1

PATH=$PATH:/usr/sbin:/sbin
case "$act" in
	stop )
		crm resource stop $rsc	
		rc=$?
		;;
	start )
		crm resource start $rsc 
		rc=$?
		;;
	migrate )
		# we might need to discuss, if we want to use the options
		#   lifetime (to remove the migration contstraint later)
		#         the stickiness should leave the resource on the
		#         migration node, but a restart would than place
		#         the resource on the original node -> its a point 
		#         of the use case -> maybe we need additional parameters
		#         for this helper script
		#   force ( to overload high stickiness values )
		crm resource migrate $rsc $node
		rc=$?
		;;
	migrate-master )
		# this should be helping to migrate the enq-repl master
		;;
	* )
		rc=2
		;;
esac
echo "$0 exists with rc=$rc"
exit $rc
